#!/bin/bash

. ~/project/dotfiles/githubrc
. ~/project/dockerfiles/.dockerfunc.bash
. ~/project/gcloudfunc/gcloudfunc.bash
. ~/project/kubefunc/kubefunc.bash

alias ls='ls --color'
alias ll='ls -l'

source ${HOME}/.kube-ps1/kube-ps1.sh
PS1='[\W $(kube_ps1)]\$ '

export PATH=${HOME}/bin:${PATH}:${HOME}/.local/bin

export GOOGLE_PROJECT=${GOOGLE_PROJECT:-$(gcloud config get-value project 2>/dev/null)}

# set gopath
export GOPATH=${HOME}/gopath
export PATH=${PATH}:${GOPATH}/bin
