#!/bin/bash

. ~/project/env/dotfiles/aliases
. ~/project/env/dotfiles/githubrc
. ~/project/env/dockerfiles/.dockerfunc.bash
. ~/project/env/gcloudfunc/gcloudfunc.bash
. ~/project/env/kubefunc/kubefunc.bash
. ~/project/env/kube-ps1/kube-ps1.sh

PS1='[\W $(kube_ps1)]\$ '

export PATH=${HOME}/bin:${PATH}:${HOME}/.local/bin

export GOOGLE_PROJECT=${GOOGLE_PROJECT:-$(gcloud config get-value project 2>/dev/null)}

# set gopath
export GOPATH=${HOME}/gopath
export PATH=${PATH}:${GOPATH}/bin
