#!/bin/bash

. ${HOME}/project/env/dotfiles/githubrc
. ${HOME}/project/env/dotfiles/vsorc
. ${HOME}/project/env/dotfiles/codeserverrc
. ${HOME}/project/env/dotfiles/selkies-env
. ${HOME}/project/env/dotfiles/sagent
. ${HOME}/project/env/dockerfiles/.dockerfunc.bash
. ${HOME}/project/env/gcloudfunc/gcloudfunc.bash
. ${HOME}/project/env/kubefunc/kubefunc.bash
. ${HOME}/project/env/kube-ps1/kube-ps1.sh

. ${HOME}/project/env/dotfiles/aliases

PS1='[\W $(kube_ps1)]\$ '

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

export PATH=${HOME}/bin:${PATH}:${HOME}/.local/bin

export GOOGLE_PROJECT=${GOOGLE_PROJECT:-$(gcloud config get-value project 2>/dev/null)}

# set gopath
export GOPATH=${HOME}/gopath
export PATH=${PATH}:${GOPATH}/bin
