#!/bin/bash

# Source file containing:
#  export GITHUB_USERNAME="your github username"
#  export GITHUB_TOKEN="your github access token"
source ${HOME}/.github_credentials

function git-clone-my () {
  local repo_name=$1
  shift;
  [[ -z "$repo_name" ]] && echo "Usage: git-clone-my <repo name>" && return 1
  [[ -z "$GITHUB_USERNAME" ]] && echo "ERROR: missing env GITHUB_USERNAME" && return 1
  [[ -z "$GITHUB_TOKEN" ]] && echo "ERROR: missing env GITHUB_TOKEN" && return 1
  echo git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${repo_name}.git $@
}

function git-clone-private () {
  local repo_user=$1
  local repo_name=$2
  shift; shift;
  [[ -z "$repo_user" || -z "$repo_name" ]] && echo "Usage: git-clone-private <username/organization> <repo name>" && return 1
  [[ -z "$GITHUB_USERNAME" ]] && echo "ERROR: missing env GITHUB_USERNAME" && return 1
  [[ -z "$GITHUB_TOKEN" ]] && echo "ERROR: missing env GITHUB_TOKEN" && return 1
  echo git clone https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${repo_user}/${repo_name}.git $@
}